--------------------------------------------------------
--  파일이 생성됨 - 금요일-1월-31-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TBL_READ_BOOK
--------------------------------------------------------

  CREATE TABLE "ADMIN"."TBL_READ_BOOK" 
   (	"RB_SEQ" NUMBER, 
	"RB_BCODE" VARCHAR2(20 BYTE), 
	"RB_DATE" VARCHAR2(10 BYTE), 
	"RB_STIME" VARCHAR2(10 BYTE), 
	"RB_RTIME" NUMBER(10,3), 
	"RB_SUBJECT" NVARCHAR2(20), 
	"TB_TEXT" NVARCHAR2(400), 
	"RB_STAR" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into ADMIN.TBL_READ_BOOK
SET DEFINE OFF;
Insert into ADMIN.TBL_READ_BOOK (RB_SEQ,RB_BCODE,RB_DATE,RB_STIME,RB_RTIME,RB_SUBJECT,TB_TEXT,RB_STAR) values (32,'979-11-625407-1-8','2020-01-16','15:04:22',9,'별ㅋㅋ','<p>ㅇㅇㅇㅇㅇ</p>',1);
Insert into ADMIN.TBL_READ_BOOK (RB_SEQ,RB_BCODE,RB_DATE,RB_STIME,RB_RTIME,RB_SUBJECT,TB_TEXT,RB_STAR) values (33,'979-11-888502-6-6','2020-01-16','15:12:12',6,'별이 다섯개?','<p>ㅇㅇㅇ</p>',5);
Insert into ADMIN.TBL_READ_BOOK (RB_SEQ,RB_BCODE,RB_DATE,RB_STIME,RB_RTIME,RB_SUBJECT,TB_TEXT,RB_STAR) values (35,'979-11-625406-7-1','2020-01-16','16:34:24',55,'머','<p>ㅇㅁㄴㄻㅇㄴㄻㅇ</p><p>ㄴㄹ</p><p>ㅁㄴㅇ</p><p>ㄹ</p><p>ㅁㄴㄹㄴㅁㅇ</p>',2);
Insert into ADMIN.TBL_READ_BOOK (RB_SEQ,RB_BCODE,RB_DATE,RB_STIME,RB_RTIME,RB_SUBJECT,TB_TEXT,RB_STAR) values (29,'979-11-888503-6-5','2020-01-16','13:46:18',5,'ㅇㄴㄻㅇㄴㄻㅇㄴㄻㄴㅇㄹ','<p>ㅁㄴ</p>',5);
--------------------------------------------------------
--  DDL for Index SYS_C007038
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."SYS_C007038" ON "ADMIN"."TBL_READ_BOOK" ("RB_SEQ") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table TBL_READ_BOOK
--------------------------------------------------------

  ALTER TABLE "ADMIN"."TBL_READ_BOOK" ADD PRIMARY KEY ("RB_SEQ")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ADMIN"."TBL_READ_BOOK" MODIFY ("RB_DATE" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."TBL_READ_BOOK" MODIFY ("RB_BCODE" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table TBL_READ_BOOK
--------------------------------------------------------

  ALTER TABLE "ADMIN"."TBL_READ_BOOK" ADD CONSTRAINT "FK_BOOKS" FOREIGN KEY ("RB_BCODE")
	  REFERENCES "ADMIN"."TBL_BOOKS" ("B_CODE") ON DELETE CASCADE ENABLE;
