--------------------------------------------------------
--  파일이 생성됨 - 금요일-1월-31-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TBL_MEMBER
--------------------------------------------------------

  CREATE TABLE "ADMIN"."TBL_MEMBER" 
   (	"M_ID" VARCHAR2(6 BYTE), 
	"M_PASSWORD" NVARCHAR2(125), 
	"M_LOGIN_DATE" NVARCHAR2(125), 
	"M_REM" NVARCHAR2(125)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into ADMIN.TBL_MEMBER
SET DEFINE OFF;
Insert into ADMIN.TBL_MEMBER (M_ID,M_PASSWORD,M_LOGIN_DATE,M_REM) values ('ttttt','tttttttt',null,null);
Insert into ADMIN.TBL_MEMBER (M_ID,M_PASSWORD,M_LOGIN_DATE,M_REM) values ('asdasd','$2a$04$EmmDZ6J4Hku.m4D7L4Zjy.IqVta300s6.KG434u8rQ86vP77tArgm',null,null);
Insert into ADMIN.TBL_MEMBER (M_ID,M_PASSWORD,M_LOGIN_DATE,M_REM) values ('12345','$2a$04$vCnVeXHv4uqSSgmKgNHzTOAUoiHSqcyuSc0kTZz9.E8BaFLS2yR8u','2020-01-13',null);
--------------------------------------------------------
--  DDL for Index SYS_C007035
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."SYS_C007035" ON "ADMIN"."TBL_MEMBER" ("M_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table TBL_MEMBER
--------------------------------------------------------

  ALTER TABLE "ADMIN"."TBL_MEMBER" ADD PRIMARY KEY ("M_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ADMIN"."TBL_MEMBER" MODIFY ("M_PASSWORD" NOT NULL ENABLE);
